version: '3'

services:
  # app:
  #   build: ./
  #   command: ./vocabulary-api
  #   depends_on:
  #     - elasticsearch
  #   restart: 'on-failure'
  #   ports:
  #     - 8080:8080
  #   links:
  #     - elasticsearch

    
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:7.10.2
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    
  postgres:
    # restart: always
    image: postgres
    environment:
      POSTGRES_DB: vocabulary
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: post1235
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data/

volumes:
  esdata:
  pgdata: